[package]
name = "draft"
version = "0.1.0"
authors = ["Yarrow Angelweed <yarrow.angelweed@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
pulldown-cmark = "0.1"
regex = "0.2"
lazy_static = "1"
structopt-derive = "0.1.6"
structopt = "0.1.7"
failure = "0.1.1"
memchr = "2.0.1"
